######################################################################
# Automatically generated by qmake (3.0) mer. mai 6 12:50:59 2015
######################################################################

TEMPLATE = app
TARGET = client
INCLUDEPATH += .

QT += core gui network widgets

# Input
HEADERS += clientWindow.h
FORMS += clientWindow.ui
SOURCES += clientMain.cpp clientWindow.cxx
RESOURCES += images.qrc
