######################################################################
# Automatically generated by qmake (3.0) mer. mai 6 09:19:27 2015
######################################################################

TEMPLATE = app
TARGET = chatterboxd
INCLUDEPATH += .

QT += core gui network widgets

# Input
HEADERS += ChatterBoxServer.h
SOURCES += ChatterBoxServer.cpp main.cpp
