######################################################################
# Automatically generated by qmake (3.0) mer. mai 6 09:20:25 2015
######################################################################

TEMPLATE = app
TARGET = chatterbox
INCLUDEPATH += .

QT += core gui network widgets

# Input
HEADERS += MainWindow.h
FORMS += MainWindow.ui
SOURCES += main.cpp MainWindow.cxx
RESOURCES += images.qrc

DISTFILES += \
    envoi.png
