######################################################################
# Automatically generated by qmake (3.0) mer. mai 6 05:09:04 2015
######################################################################

TEMPLATE = app
TARGET = serveur
INCLUDEPATH += .

QT += core gui widgets network

# Input
HEADERS += servTcp.h
SOURCES += servTcp.cpp servTcpMain.cpp
