######################################################################
# Automatically generated by qmake (3.0) mer. mai 6 11:51:51 2015
######################################################################

TEMPLATE = app
TARGET = serveur
INCLUDEPATH += .

QT += core gui network widgets

# Input
HEADERS += serveurChat.h
SOURCES += serveurChat.cpp serveurMain.cpp
