######################################################################
# Automatically generated by qmake (3.0) mer. mai 6 17:08:12 2015
######################################################################

TEMPLATE = app
TARGET = serveur
INCLUDEPATH += .

QT += core gui network widgets

# Input
HEADERS += serveurChat.h
SOURCES += serveurChat.cpp serveurMain.cpp
